spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/movie?serverTimezone=GMT&autoReconnect=false&useSSL=false"
    username: root
    password: Wzj_mysql01
    driver-class-name:  com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none # Initialize the database by using JPA in
      naming:
        # default naming strategy would cause @Column with specific name not working if the filed name is camel casing style
        # use the following stategy to be compatible with existing table schema
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use-new-id-generator-mappings: AUTO   # add auto_increment for id
        show_sql: true
        use_sql_comments: false
        format_sql: true
    database: mysql